# -------------------------------------------------------
# validator/schemas.py
# -------------------------------------------------------
# Pydantic models that define the *shape* of data flowing
# through the application.
#
# Why Pydantic?
#   - Automatic data validation (wrong types are caught)
#   - Self-documenting (shows up in Swagger docs)
#   - Easy JSON serialisation
# -------------------------------------------------------

from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime


# ---------- Incoming data models ----------

class Evidence(BaseModel):
    """
    Evidence attached to a compliance task.
    If a field is None / null it means that piece of
    evidence has NOT been provided yet.
    """
    document_id: Optional[str] = None   # e.g. "DOC-8831"
    submitted_at: Optional[str] = None  # ISO-8601 timestamp
    reviewer: Optional[str] = None      # Name of the reviewer


class ComplianceTask(BaseModel):
    """
    Represents a single compliance task from the mock
    database. This is what the JSON file stores.
    """
    task_id: str                        # Unique ID, e.g. "TASK-001"
    title: str                          # Human-readable name
    department: str                     # Owning department
    assigned_to: str                    # Person responsible
    status: str                         # "completed" | "in_progress" | "pending"
    evidence: Evidence                  # Supporting proof (may be partial)


# ---------- Outgoing data models ----------

class ValidationResult(BaseModel):
    """
    The verdict the validator engine returns after
    checking a task.

    verdict can be:
      PASS         → task genuinely completed with full evidence
      FAIL         → status says completed but evidence is missing
      NEEDS_REVIEW → task is not yet marked completed
    """
    task_id: str
    title: str
    verdict: str                        # "PASS" | "FAIL" | "NEEDS_REVIEW"
    reasons: List[str]                  # Human-readable explanation(s)
    validated_at: str                   # When the check was performed


# ---------- Reasoning Validator models ----------

class ReasoningRequest(BaseModel):
    """
    Input for the POST /reasoning-validate endpoint.

    The Dispatcher Agent (or a human) sends a task
    description + evidence, and the Reasoning Engine
    returns an intelligent verdict.

    Example:
    {
        "task_id": 1,
        "task": "Enable MFA for admin accounts",
        "evidence": {
            "api_response": true,
            "manual_status": "Done",
            "screenshot_uploaded": true
        }
    }
    """
    task_id: int = 1                    # Unique task identifier
    task: str                           # Description of the compliance task
    evidence: dict                      # Key-value pairs of evidence fields


class ReasoningResponse(BaseModel):
    """
    Standardised output from the Reasoning Validator Engine.

    Contains the verdict plus confidence/risk metrics,
    the LLM's reasoning explanation, watchdog alerts,
    and a step-by-step reasoning chain for full transparency.
    """
    task_id: int
    status: str                         # "VERIFIED" | "NON_COMPLIANT" | "NEEDS_REVIEW"
    confidence_score: int               # 0-100 (how sure are we?)
    risk_score: int                     # 0-100 (how risky is this?)
    reason: str                         # Human-readable explanation
    concerns: List[str] = []            # Specific concerns found
    recommendation: str = ""            # Action item for the audit team
    suspicion_flags: List[str] = []     # Deterministic flags triggered
    severity: str = "MEDIUM"            # LOW | MEDIUM | HIGH | CRITICAL
    task_category: str = "default"      # mfa | firewall | password | training | audit
    evidence_quality: str = "unknown"   # strong | moderate | weak
    reasoning_chain: list = []          # Step-by-step trace of decisions
    watchdog_alert: bool = False        # Whether a watchdog alert was triggered
    alert_level: str = "CLEAR"          # CLEAR | INFO | WARNING | CRITICAL
    llm_used: bool = False              # Was the LLM used for reasoning?
    llm_model: Optional[str] = None     # Which model (e.g., "phi3")
    timestamp: str = ""                 # When the validation was performed


# ---------- Watchdog models ----------

class WatchdogAlert(BaseModel):
    """
    A watchdog alert generated by the Spectre-Sentinel
    integration layer when suspicious activity is detected.
    """
    watchdog_alert: bool                # True if alert was triggered
    alert_level: str                    # CRITICAL | WARNING | INFO | CLEAR
    alert_reason: str                   # Why the alert was triggered
    recommended_action: str             # What should happen next
    escalation_required: bool           # Whether a human must act now
    alert_timestamp: str                # When the alert was generated
    source_task_id: Optional[int] = None
    source_risk_score: int = 0
    source_status: str = ""


