# -------------------------------------------------------
# validator/train_model.py
# -------------------------------------------------------
# Trains the compliance ML model using the synthetic
# training data generated by generate_training_data.py.
#
# This script:
#   1. Loads the CSV training data
#   2. Splits into train/test sets (80/20)
#   3. Trains a Random Forest Classifier (risk level)
#   4. Trains a Random Forest Regressor (compliance score)
#   5. Evaluates accuracy on the test set
#   6. Saves both models to a .pkl file
#
# Run this script after generating data:
#   python -m validator.train_model
# -------------------------------------------------------

import pathlib
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    mean_absolute_error,
    r2_score,
)

# -------------------------------------------------------
# File Paths
# -------------------------------------------------------
DATA_DIR = pathlib.Path(__file__).parent.parent / "data"
TRAINING_DATA_FILE = DATA_DIR / "training_data.csv"
MODEL_FILE = DATA_DIR / "compliance_model.pkl"

# -------------------------------------------------------
# Feature and Label Columns
# -------------------------------------------------------
FEATURE_COLUMNS = [
    "mfa_enabled",
    "firewall_active",
    "password_min_length",
    "special_chars_required",
    "total_tasks",
    "completed_tasks",
    "evidence_complete_tasks",
]

RISK_LEVEL_NAMES = {0: "LOW", 1: "MEDIUM", 2: "HIGH", 3: "CRITICAL"}


# -------------------------------------------------------
# Training Function
# -------------------------------------------------------

def train():
    """
    Train both models and save them to disk.

    Returns
    -------
    dict
        Training results including accuracy metrics.
    """

    # --------------------------------------------------
    # 1. Load training data
    # --------------------------------------------------
    print("  Loading training data...")
    if not TRAINING_DATA_FILE.exists():
        print(
            "  ERROR: Training data not found!"
            "\n  Run this first: python -m validator.generate_training_data"
        )
        return None

    df = pd.read_csv(TRAINING_DATA_FILE)
    print(f"  Loaded {len(df)} samples with {len(FEATURE_COLUMNS)} features")

    # --------------------------------------------------
    # 2. Separate features and labels
    # --------------------------------------------------
    X = df[FEATURE_COLUMNS]
    y_risk = df["risk_level"]
    y_score = df["compliance_score"]

    # --------------------------------------------------
    # 3. Split into train and test sets
    # --------------------------------------------------
    # Using 80% for training, 20% for testing
    # random_state ensures reproducibility
    X_train, X_test, y_risk_train, y_risk_test = train_test_split(
        X, y_risk, test_size=0.2, random_state=42, stratify=y_risk
    )

    # We need the same split indices for the score labels
    _, _, y_score_train, y_score_test = train_test_split(
        X, y_score, test_size=0.2, random_state=42, stratify=y_risk
    )

    print(f"  Training set: {len(X_train)} samples")
    print(f"  Test set:     {len(X_test)} samples")
    print()

    # --------------------------------------------------
    # 4. Train the Risk Level Classifier
    # --------------------------------------------------
    print("  Training Risk Level Classifier (Random Forest)...")
    risk_classifier = RandomForestClassifier(
        n_estimators=100,       # 100 decision trees in the forest
        max_depth=10,           # Limit depth to prevent overfitting
        min_samples_split=5,    # Minimum samples to split a node
        random_state=42,        # Reproducibility
        n_jobs=-1,              # Use all CPU cores for speed
    )
    risk_classifier.fit(X_train, y_risk_train)

    # Evaluate the classifier
    y_risk_pred = risk_classifier.predict(X_test)
    risk_accuracy = accuracy_score(y_risk_test, y_risk_pred)

    print(f"  Risk Classifier Accuracy: {risk_accuracy:.1%}")
    print()
    print("  Classification Report:")
    print(
        classification_report(
            y_risk_test,
            y_risk_pred,
            target_names=["LOW", "MEDIUM", "HIGH", "CRITICAL"],
            zero_division=0,
        )
    )

    # --------------------------------------------------
    # 5. Train the Compliance Score Regressor
    # --------------------------------------------------
    print("  Training Compliance Score Regressor (Random Forest)...")
    score_regressor = RandomForestRegressor(
        n_estimators=100,
        max_depth=10,
        min_samples_split=5,
        random_state=42,
        n_jobs=-1,
    )
    score_regressor.fit(X_train, y_score_train)

    # Evaluate the regressor
    y_score_pred = score_regressor.predict(X_test)
    score_mae = mean_absolute_error(y_score_test, y_score_pred)
    score_r2 = r2_score(y_score_test, y_score_pred)

    print(f"  Score Regressor MAE:  {score_mae:.2f} points")
    print(f"  Score Regressor R^2:  {score_r2:.4f}")
    print()

    # --------------------------------------------------
    # 6. Feature Importances
    # --------------------------------------------------
    # This tells us which features the model considers
    # most important for predicting risk — useful for
    # the reasoning engine later.
    importances = dict(
        zip(FEATURE_COLUMNS, risk_classifier.feature_importances_)
    )

    # Sort by importance (highest first)
    sorted_importances = dict(
        sorted(importances.items(), key=lambda x: x[1], reverse=True)
    )

    print("  Feature Importances (Risk Classifier):")
    print(f"  {'Feature':<30} {'Importance':<10}")
    print(f"  {'-'*30} {'-'*10}")
    for feat, imp in sorted_importances.items():
        bar = "#" * int(imp * 50)
        print(f"  {feat:<30} {imp:.4f}  {bar}")
    print()

    # --------------------------------------------------
    # 7. Save the trained models
    # --------------------------------------------------
    print("  Saving trained models...")
    model_package = {
        "risk_classifier": risk_classifier,
        "score_regressor": score_regressor,
        "feature_columns": FEATURE_COLUMNS,
        "risk_level_names": RISK_LEVEL_NAMES,
        "feature_importances": sorted_importances,
        "metrics": {
            "risk_accuracy": risk_accuracy,
            "score_mae": score_mae,
            "score_r2": score_r2,
        },
    }

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(model_package, MODEL_FILE)
    print(f"  Model saved to: {MODEL_FILE}")

    return model_package


# -------------------------------------------------------
# Main — run this to train the model
# -------------------------------------------------------

if __name__ == "__main__":
    print("=" * 60)
    print("  AUTO-AUDITOR — MODEL TRAINING")
    print("=" * 60)
    print()

    result = train()

    if result is not None:
        metrics = result["metrics"]
        print()
        print("=" * 60)
        print("  TRAINING COMPLETE!")
        print(f"  Risk Classifier Accuracy: {metrics['risk_accuracy']:.1%}")
        print(f"  Score Regressor MAE:      {metrics['score_mae']:.2f}")
        print(f"  Score Regressor R^2:      {metrics['score_r2']:.4f}")
        print("=" * 60)
    else:
        print()
        print("  Training failed. See errors above.")
